### PR TITLE
A few fixes for mapcore gallery

### PR DESCRIPTION
**Pull request by Tehsurfer**
- Only show card if data for it exists
 - Import elementui components
 - rename 'data' prop to 'entry'
 - disable eslint on build
 - create seperate main files for build and running locally

### CODE REVIEW

**Review by hsorby — CHANGES_REQUESTED** [review]
Looks pretty good to me but I would prefer the prop to be called `details` rather than `entry`.

**Comment by hsorby** [comment]
With these changes we should also correct the url in the package.json file.

**Comment by alan-wu** [comment]
Would not this make more sense to not include undefined item in the windowedItems instead?

**Comment by Tehsurfer** [comment]
The work done here is now included in #5 

( I need the above changes for development )

**Pull request closed without merging**
